from enum import Enum


class EventCode(Enum):
    """
    BT Sig Defined HCI Event Codes
    """

    DICON_COMPLETE = 0x05
    ENC_CHANGE = 0x08
    READ_REMOTE_VERSION_INFO_COMPLETE = 0x0C
    COMMAND_COMPLETE = 0x0E
    COMMAND_STATUS = 0x0F
    HARDWARE_ERROR = 0x10
    NUM_COMPLETED_PACKETS = 0x13
    DATA_BUFF_OVERFLOW = 0x1A
    ENC_KEY_REFRESH_COMPLEET = 0x30
    LE_META = 0x3E
    AUTH_PAYLOAD_TIMEOUT_EXPIRED = 0x57
    VENDOR_SPEC = 0xFF

class EventSubcode(Enum):
    CONNECTION_COMPLETE = 0x1
    ADVERTISING_REPORT = 0x2
    CONNECTION_UPDATE = 0x3
    READ_REMOTE_FEATURES_COMPLETE = 0x4
    LONG_TERM_KEY_REQUEST = 0x5
    REMOTE_CONNECTION_PARAMETER_REQUEST = 0x6
    DATA_LENGTH_CHANGE = 0x7
    READ_LOCAL_P256_PUBLIC_KEY_COMPLETE = 0x8
    GENERATE_DHKEY_COMPLETE = 0x9
    ENHANCED_CONNECTION_COMPLETE = 0xA
    DIRECTED_ADVERTISIING_REPORT = 0xB
    PHY_UPDATE_COMPLETE = 0xC
    EXTENDED_ADVERTISING_REPORT = 0xD
    PERIODIC_ADVERTISING_SYNC_ESTABLISHED = 0xE
    PERIODIC_ADVERTISING_REPORT = 0xF
    PERIODIC_ADVERTISING_SYNC_LOST = 0x10
    SCAN_TIMEOUT = 0x11
    ADVERTISING_SET_TERMINATED = 0x12
    SCAN_REQUEST_RECEIVED = 0x13
    CHANNEL_SELECTION_ALGORITHM = 0x14
    CONNECTIONLESS_IRQ_REPORT = 0x15
    CONNECTION_IQ_REPORT = 0x16
    CTE_REQUEST_FAILED = 0x17
    PERIODIC_ADVERTISING_SYNC_TRANSER_RECEIVED = 0x18
    CIS_ESTABLISHED = 0x19
    CIS_REQUEST = 0x1A
    CREATE_BIG_COMPLETE = 0x1B
    TERMINATE_BIG_COMPLETE = 0x1C
    BIG_SYNC_ESTABLISHED = 0x1D
    BIG_SYNC_LOST = 0x1E
    REQUEST_PEER_SCA_COMPLETE = 0x1F
    PATH_LOSS_THRESHOLD = 0x20
    TRANSMIT_POWER_REPORTING = 0x21
    BIG_INFO_ADVERTISING_REPORT = 0x22

class StatusCode(Enum):
    LL_SUCCESS = 0x00
    LL_ERROR_CODE_UNKNOWN_HCI_CMD = 0x01
    LL_ERROR_CODE_UNKNOWN_CONN_ID = 0x2
    LL_ERROR_CODE_HW_FAILURE = 0x03
    LL_ERROR_CODE_PAGE_TIMEOUT = 0x04
    LL_ERROR_CODE_AUTH_FAILURE = 0x05
    LL_ERROR_CODE_PIN_KEY_MISSING = 0x06
    LL_ERROR_CODE_MEM_CAP_EXCEEDED = 0x07
    LL_ERROR_CODE_CONN_TIMEOUT = 0x08
    LL_ERROR_CODE_CONN_LIMIT_EXCEEDED = 0x09
    LL_ERROR_CODE_SYNCH_CONN_LIMIT_EXCEEDED = 0x0A
    LL_ERROR_CODE_ACL_CONN_ALREADY_EXISTS = 0x0B
    LL_ERROR_CODE_CMD_DISALLOWED = 0x0C
    LL_ERROR_CODE_CONN_REJ_LIMITED_RESOURCES = 0x0D
    LL_ERROR_CODE_CONN_REJECTED_SECURITY_REASONS = 0x0E
    LL_ERROR_CODE_CONN_REJECTED_UNACCEPTABLE_BDADDR = 0x0F
    LL_ERROR_CODE_CONN_ACCEPT_TIMEOUT_EXCEEDED = 0x10
    LL_ERROR_CODE_UNSUPPORTED_FEATURE_PARAM_VALUE = 0x11
    LL_ERROR_CODE_INVALID_HCI_CMD_PARAMS = 0x12
    LL_ERROR_CODE_REMOTE_USER_TERM_CONN = 0x13
    LL_ERROR_CODE_REMOTE_DEVICE_TERM_CONN_LOW_RESOURCES = 0x14
    LL_ERROR_CODE_REMOTE_DEVICE_TERM_CONN_POWER_OFF = 0x15
    LL_ERROR_CODE_CONN_TERM_BY_LOCAL_HOST = 0x16
    LL_ERROR_CODE_REPEATED_ATTEMPTS = 0x17
    LL_ERROR_CODE_PAIRING_NOT_ALLOWED = 0x18
    LL_ERROR_CODE_UNKNOWN_LMP_PDU = 0x19
    LL_ERROR_CODE_UNSUPPORTED_REMOTE_FEATURE = 0x1A
    LL_ERROR_CODE_SCO_OFFSET_REJ = 0x1B
    LL_ERROR_CODE_SCO_INTERVAL_REJ = 0x1C
    LL_ERROR_CODE_SCO_AIR_MODE_REJ = 0x1D
    LL_ERROR_CODE_INVALID_LMP_PARAMS = 0x1E
    LL_ERROR_CODE_UNSPECIFIED_ERROR = 0x1F
    LL_ERROR_CODE_UNSUPPORTED_LMP_PARAM_VAL = 0x20
    LL_ERROR_CODE_ROLE_CHANGE_NOT_ALLOWED = 0x21
    LL_ERROR_CODE_LMP_LL_RESP_TIMEOUT = 0x22
    LL_ERROR_CODE_LMP_ERR_TRANSACTION_COLLISION = 0x23
    LL_ERROR_CODE_LMP_PDU_NOT_ALLOWED = 0x24
    LL_ERROR_CODE_ENCRYPT_MODE_NOT_ACCEPTABLE = 0x25
    LL_ERROR_CODE_LINK_KEY_CAN_NOT_BE_CHANGED = 0x26
    LL_ERROR_CODE_REQ_QOS_NOT_SUPPORTED = 0x27
    LL_ERROR_CODE_INSTANT_PASSED = 0x28
    LL_ERROR_CODE_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 0x29
    LL_ERROR_CODE_DIFFERENT_TRANSACTION_COLLISION = 0x2A
    LL_ERROR_CODE_RESERVED1 = 0x2B
    LL_ERROR_CODE_QOS_UNACCEPTABLE_PARAM = 0x2C
    LL_ERROR_CODE_QOS_REJ = 0x2D
    LL_ERROR_CODE_CHAN_ASSESSMENT_NOT_SUPPORTED = 0x2E
    LL_ERROR_CODE_INSUFFICIENT_SECURITY = 0x2F
    LL_ERROR_CODE_PARAM_OUT_OF_MANDATORY_RANGE = 0x30
    LL_ERROR_CODE_RESERVED2 = 0x31
    LL_ERROR_CODE_ROLE_SWITCH_PENDING = 0x32
    LL_ERROR_CODE_RESERVED3 = 0x33
    LL_ERROR_CODE_RESERVED_SLOT_VIOLATION = 0x34
    LL_ERROR_CODE_ROLE_SWITCH_FAILED = 0x35
    LL_ERROR_CODE_EXTENDED_INQUIRY_RESP_TOO_LARGE = 0x36
    LL_ERROR_CODE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 0x37
    LL_ERROR_CODE_HOST_BUSY_PAIRING = 0x38
    LL_ERROR_CODE_CONN_REJ_NO_SUITABLE_CHAN_FOUND = 0x39
    LL_ERROR_CODE_CONTROLLER_BUSY = 0x3A
    LL_ERROR_CODE_UNACCEPTABLE_CONN_INTERVAL = 0x3B
    LL_ERROR_CODE_ADV_TIMEOUT = 0x3C
    LL_ERROR_CODE_CONN_TERM_MIC_FAILURE = 0x3D
    LL_ERROR_CODE_CONN_FAILED_TO_ESTABLISH = 0x3E
    LL_ERROR_CODE_MAC_CONN_FAILED = 0x3F
    LL_ERROR_CODE_COARSE_CLK_ADJ_REJ = 0x40
    LL_ERROR_CODE_TYPE0_SUBMAP_NOT_DEF = 0x41
    LL_ERROR_CODE_UNKNOWN_ADV_ID = 0x42
    LL_ERROR_CODE_LIMIT_REACHED = 0x43
    LL_ERROR_CODE_OP_CANCELLED_BY_HOST = 0x44
    LL_ERROR_CODE_PKT_TOO_LONG = 0x45

    # Cordio returns an 0xFF when the status isnt properly set
    # Most likely the feature is not conditionally compiled in
    LL_DECODE_FAILURE = 0xFF
