name: black-format-check
on: 
  workflow_dispatch:
  pull_request:
    branches: ["main"]
jobs:
  format_check:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --exclude docs"
