name: black-format-run
on: [workflow_dispatch]
jobs:
  format_check:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --exclude docs"
  format_run:
    name: runner / black
    runs-on: ubuntu-latest
    if: jobs.format_check.result == 'failure'
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'black-format bot reformatting.'
          push: true
